// @letterblack/lbe-core — source package entry point.
export {
    createLBE,
    sandbox,
    validateCommand,
    appendAudit,
    createBackup,
    restoreBackup,
    signEd25519,
    verifyEd25519,
    generateKeyPair,
    createLogger,
    deepFreeze,
    checkInvariants,
    assertInvariants,
    InvariantGateError,
    addLocalPolicyRule,
    loadLocalPolicy,
    evaluateLocalPolicy,
    proposePolicyRule,
    createKeyStore,
} from './src/core/index.js';

export {
    execute,
    getRuntimeInfo,
    loadWasmEngine,
    runValidationPipeline,
    checkNonce,
    checkRateLimit,
    computeAuditHash,
    classifyRisk,
    shouldRollback,
    evaluatePolicyDecision,
    evaluateSchemaDecision,
} from './runtime/engine.js';
